In [2]:
import tensorflow as tf

x = tf.constant(1)
y = tf.constant(2)
z = tf.constant(3)
a = x * y + z

sess = tf.Session()  # 텐서플로우는 무조건 세션에 저장을 시켜서 실행해야한다.
b = sess.run(a)  # sess.실행 (식)
print(b)

5


In [4]:
a = tf.constant([[1, 2], [3, 4], [5, 6]])
print(a.dtype)
print(a.shape)
print(sess.run(tf.rank(a)))

<dtype: 'int32'>
(3, 2)
2


In [6]:
a = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
b = tf.reshape(a, [3, 4])
c = tf.transpose(b) # transpose() : 행렬 연산 수행에 사용
print(sess.run(b))
print(sess.run(c))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [7]:
a = tf.constant([1, 2, 3, 4, 5])
b = tf.constant([-1, -1, -1, -1, -1])
c = a * b    # 두개의 행렬 연산을 편하게 할 수 있음
print(sess.run(c))

[-1 -2 -3 -4 -5]


In [8]:
# tesnorflow는 관계연산 수행 함수도 제공
a = tf.constant([1, 2, 3, 4, 5])
b = tf.constant([1, 4, 6, 4, 9])
c = tf.equal(a, b)
print(sess.run(c))

[ True False False  True False]


In [ ]:
# 자료형 타입

# 변하지 않는 상수 저장을 위한 고정 크기 메모리
# 초기화 되면서 메모리 크기와 type이 결정
# 세션 실행 시 자동으로 초기화
# 함수 원형 : tf.constant(value, dtype, shape) 2번째 3번째 파라미터는 생략 가능.
tf.constant() 

# 학습 데이터를 저장힉 위한 가변 크기 메모리
# 자료 구조만 정해주고, 나중에 data를 공급받음
# 반복적으로 feeding 가능  -  학습 시 학습 데이터를, 테스트 시에는 테스트 데이터를 전달 가능
# 함수원형 : tf.placeholder(dtype, shape)
tf.placeholder()

# 학습 파라미터를 저장하기 위한 고정 크기 메모리
# 반복적으로 읽고 쓰기 기능
# 반드시 초기화 되어야 함
# 함수 원형 : tf.Variable(value, dtype, shape) dtype와 shape는 생략 가능
tf.Variable()

In [11]:
# 예제
input_data = [1, 2, 3, 4, 5]
x = tf.placeholder(dtype = tf.float32)
w = tf.Variable([2.0])
b = tf.constant([1.4])
y = w * x + b

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

out1 = sess.run(y, feed_dict = {x : [1,2,3]})
out2 = sess.run(y, feed_dict = {x : [-1.0, -2.0]})
print(out1)
print(out2)

[3.4 5.4 7.4]
[-0.6 -2.6]


In [12]:
import numpy as np

In [13]:
a = tf.constant(2.0)
print(a)
print(sess.run(a))

Tensor("Const_16:0", shape=(), dtype=float32)
2.0


In [16]:
print(a.shape)
if a.shape == () : print("차원 0")
print(type(a.shape))

()
차원 0
<class 'tensorflow.python.framework.tensor_shape.TensorShape'>


In [17]:
b = tf.constant([2.0])
print(sess.run(b)) # 대괄호 출력은 벡터임을 나타낸다.

[2.]


In [20]:
a = tf.constant(4)
b = tf.constant([4])
print(a)
print(b)

Tensor("Const_22:0", shape=(), dtype=int32)
Tensor("Const_23:0", shape=(1,), dtype=int32)


In [21]:
a_ = sess.run(a)
b_ = sess.run(b)
print(a_, type(a_))
print(b_, type(b_))

4 <class 'numpy.int32'>
[4] <class 'numpy.ndarray'>


In [22]:
print(b.shape)
print("length", b.shape[0])

(1,)
length 1


In [23]:
c = tf.constant([2, 3, 4])
print(c)
print(c.shape)
print("length", c.shape[0])

Tensor("Const_24:0", shape=(3,), dtype=int32)
(3,)
length 3


In [24]:
m = tf.constant([[1, 2], [3, 4], [5, 6]])
print(m)
print(m.shape)
print("행 ", m.shape[0])
print("열 ", m.shape[1])

Tensor("Const_25:0", shape=(3, 2), dtype=int32)
(3, 2)
행  3
열  2


In [25]:
# tensorflow는 jagged array형태를 지원하지 않는다.
a = [[1, 2], [3, 4, 5]]
print(a)
b = tf.constant([[1, 2], [3, 4, 5]])
print(b)

[[1, 2], [3, 4, 5]]


ValueError: Argument must be a dense tensor: [[1, 2], [3, 4, 5]] - got shape [2], but wanted [2, 2].

In [27]:
a = tf.constant([1, 2, 3, 4, 5, 6])
print(a.shape)
b = tf.constant([[1, 2, 3, 4, 5, 6]])
print(b.shape.as_list())
c = tf.constant([[1], [2], [3], [4], [5], [6]])
print(c.shape.as_list())
d = tf.constant(np.array([[1, 2], [3, 4], [5, 6]]))
print(d.shape.as_list())

(6,)
[1, 6]
[6, 1]
[3, 2]


In [30]:
print(sess.run(tf.constant(0, shape= [4 ,2]))) # 행렬 0으로 초기화 시켜 생성할 때
print(sess.run(tf.constant([0, 1, 2], shape = [4 , 2]))) # 행렬을 만들 때 제일 마지막 숫자로 채워 넣는다.

[[0 0]
 [0 0]
 [0 0]
 [0 0]]
[[0 1]
 [2 2]
 [2 2]
 [2 2]]


In [31]:
a = tf.constant([[1, 2, 3], [4, 5, 6]])
b = tf.transpose(a)
print(a.shape, b.shape)

(2, 3) (3, 2)


In [32]:
# 행 벡터를 열 벡터로 변환
a = tf.constant([[1, 2, 3, 4]])
b = tf.transpose(a)
print(sess.run(a))
print(sess.run(b))
print(a.shape)
print(b.shape)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
(1, 4)
(4, 1)


In [35]:
# transpose()는 다차원 행렬에서만 적용시킬 수 있다.
a = tf.constant([1, 2, 3, 4])
b = tf.transpose(a)
print(a.shape, b.shape)

(4,) (4,)


In [36]:
# 연산의 연산은 같은 구조에서만 가능하다.
a = tf.constant([1, 2, 3, 4, 5, 6])
b = tf.constant([2, 3, 4, 5, 6])
a * b

ValueError: Dimensions must be equal, but are 6 and 5 for 'mul_6' (op: 'Mul') with input shapes: [6], [5].

In [37]:
print(a.op)

name: "Const_38"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_INT32
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_INT32
      tensor_shape {
        dim {
          size: 6
        }
      }
      tensor_content: "\001\000\000\000\002\000\000\000\003\000\000\000\004\000\000\000\005\000\000\000\006\000\000\000"
    }
  }
}



In [38]:
print(c.op)

name: "Const_28"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_INT32
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_INT32
      tensor_shape {
        dim {
          size: 6
        }
        dim {
          size: 1
        }
      }
      tensor_content: "\001\000\000\000\002\000\000\000\003\000\000\000\004\000\000\000\005\000\000\000\006\000\000\000"
    }
  }
}



In [39]:
# 관계연산 함수
a = tf.constant([1, 2, 3, 4, 5])
b = tf.constant([1, 4, 6, 4, 9])
c = tf.equal(a, b)
print(sess.run(c))

[ True False False  True False]


In [40]:
a = tf.constant([1, 22, 23, 4, 50])
b = tf.equal(a, 22)
print(sess.run(b))

[False  True False False False]


In [41]:
# 크기 비교 함수
a = tf.constant([1, 22, 23, 4, 50])
b = tf.constant([1, 2, 6, 4, 9])
c = tf.greater(a, b)
print(sess.run(c))

[False  True  True False  True]


In [43]:
b = tf.placeholder(tf.float32)
c = tf.placeholder(dtype = tf.float32)
print(b)
print(c)

Tensor("Placeholder_5:0", dtype=float32)
Tensor("Placeholder_6:0", dtype=float32)


In [44]:
# placeholder는 가변적이지만 항상 미리 데이터타입을 선언해줘야한다.
a = tf.placeholder()

TypeError: placeholder() missing 1 required positional argument: 'dtype'

In [46]:
a = tf.placeholder(tf.float32)
print(sess.run(a, feed_dict = {a : [1.0 ,2.0, 3.0]}))

[1. 2. 3.]


In [47]:
# placeholder는 미리 데이터타입을 정의해주기때문에 정수형을 넣어도 실수형으로 변환되어서 저장된다.
a = tf.placeholder(tf.float32)
print(sess.run(a, feed_dict = {a : [1, 2, 3]}))

[1. 2. 3.]


In [49]:
dic = {}
dic = {"item": "mouse", "qty" : 5}
dic["item"] = "monitor"
print(dic["item"])

dic = {1.3 : "mouse", 4 : 5}
print(dic[1.3], dic[4])

monitor
mouse 5


In [50]:
# 리스트 타입은 해쉬 키로 사용할 수 없다.
a = []
dic = {a : [1, 2, 3, 4, 5]}

TypeError: unhashable type: 'list'

In [51]:
# numpy 객체 또한 해쉬 키로 사용할 수 없다.
a = np.array([])
dic = {a:[1,2,3,4,5]}

TypeError: unhashable type: 'numpy.ndarray'

In [52]:
# tensorflow는 가능하다.
a = tf.placeholder(tf.float32)
b = {a:[1, 2,3, 4, 5]}
print(b)
c = {a: np.array([1, 2, 3, 4, 5])}
print(c)

{<tf.Tensor 'Placeholder_10:0' shape=<unknown> dtype=float32>: [1, 2, 3, 4, 5]}
{<tf.Tensor 'Placeholder_10:0' shape=<unknown> dtype=float32>: array([1, 2, 3, 4, 5])}


In [54]:
# Variable 초기화
input_data = [1, 2, 3, 4, 5]
w = tf.Variable(input_data)
print(w)

<tf.Variable 'Variable_4:0' shape=(5,) dtype=int32_ref>


In [55]:
w = tf.Variable(input_data, dtype = tf.float32)
print(w)

<tf.Variable 'Variable_5:0' shape=(5,) dtype=float32_ref>


In [56]:
init = tf.global_variables_initializer()
print(init)

name: "init_3"
op: "NoOp"
input: "^Variable/Assign"
input: "^Variable_1/Assign"
input: "^Variable_2/Assign"
input: "^Variable_4/Assign"
input: "^Variable_5/Assign"



In [57]:
# placeholder는 실행해보지 않으면 오류를 알 수없다. shape 다르기 때문에 연산 불가. 
a = tf.placeholder(tf.float32)
b = tf.constant([1.0, 2.0, 3.0, 4.0])
c = a * b
result = sess.run(c, feed_dict={a: [1, 2, 3, 4, 5]})

InvalidArgumentError: Incompatible shapes: [4] vs. [5]
	 [[node mul_7 (defined at <ipython-input-57-9c9ae78c2f01>:4) ]]

Errors may have originated from an input operation.
Input Source operations connected to node mul_7:
 Placeholder_11 (defined at <ipython-input-57-9c9ae78c2f01>:2)	
 Const_45 (defined at <ipython-input-57-9c9ae78c2f01>:3)

Original stack trace for 'mul_7':
  File "C:\Users\82106\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\82106\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\82106\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\82106\Anaconda3\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Users\82106\Anaconda3\lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
  File "C:\Users\82106\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2854, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2880, in _run_cell
    return runner(coro)
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3057, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3248, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-57-9c9ae78c2f01>", line 4, in <module>
    c = a * b
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 884, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1180, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 6878, in mul
    "Mul", x=x, y=y, name=name)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()


In [58]:
# 결과갑 튜플로도 반환받을 수 있다.
a_, c_ = sess.run([a, c], feed_dict = {a : [1, 2, 3, 4, 5]})
print(a_)
print(c_)

InvalidArgumentError: Incompatible shapes: [4] vs. [5]
	 [[node mul_7 (defined at <ipython-input-57-9c9ae78c2f01>:4) ]]

Errors may have originated from an input operation.
Input Source operations connected to node mul_7:
 Placeholder_11 (defined at <ipython-input-57-9c9ae78c2f01>:2)	
 Const_45 (defined at <ipython-input-57-9c9ae78c2f01>:3)

Original stack trace for 'mul_7':
  File "C:\Users\82106\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\82106\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\82106\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\82106\Anaconda3\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Users\82106\Anaconda3\lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
  File "C:\Users\82106\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2854, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2880, in _run_cell
    return runner(coro)
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3057, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3248, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-57-9c9ae78c2f01>", line 4, in <module>
    c = a * b
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 884, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1180, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 6878, in mul
    "Mul", x=x, y=y, name=name)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()


In [59]:
a_, _, _ = sess.run([a, c, d], feed_dict = {a : [1, 2, 3, 4, 5]})
print(a_)

InvalidArgumentError: Incompatible shapes: [4] vs. [5]
	 [[node mul_7 (defined at <ipython-input-57-9c9ae78c2f01>:4) ]]

Errors may have originated from an input operation.
Input Source operations connected to node mul_7:
 Placeholder_11 (defined at <ipython-input-57-9c9ae78c2f01>:2)	
 Const_45 (defined at <ipython-input-57-9c9ae78c2f01>:3)

Original stack trace for 'mul_7':
  File "C:\Users\82106\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\82106\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\82106\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\82106\Anaconda3\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Users\82106\Anaconda3\lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
  File "C:\Users\82106\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\82106\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\82106\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2854, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2880, in _run_cell
    return runner(coro)
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3057, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3248, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\82106\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-57-9c9ae78c2f01>", line 4, in <module>
    c = a * b
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 884, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1180, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 6878, in mul
    "Mul", x=x, y=y, name=name)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Users\82106\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()


# 심화학습

In [61]:
a = tf.Variable([1.0, 2, 3, 4, 5])
b = a * 10.0
print(sess.run(b, feed_dict = {a: [3 , 4, 5, 6.0, 9.0]}))

[30. 40. 50. 60. 90.]


In [62]:
print(sess.run(b, feed_dict = {a : [3, 4, 5, 6.0, 9.0], b : [1.0, 2, 2, 2, 2]}))

[1. 2. 2. 2. 2.]
